### ISSUE TITLE
播放视频退出全屏后，整个页面黑屏

### ISSUE THREAD

**Issue by mojun** [yangchong211/YCWebView#123]
初步怀疑是以下方法
`
private void fullViewAddView(View view) {
        //增强逻辑判断，尤其是getWindow()
        if (context!=null && context instanceof Activity){
            Activity activity = (Activity) context;
            if (activity.getWindow()!=null){
                FrameLayout decor = (FrameLayout) activity.getWindow().getDecorView();
                videoFullView = new FullscreenHolder(activity);
                videoFullView.addView(view);
                X5LogUtils.i("--Video-----onShowCustomView----添加view到decorView容齐中---");
                decor.addView(videoFullView);
            }
        }
    }
`
添加到decorView上面的videoFullView未被移除掉
接下来只能先重新整个类

**Comment by mojun** [comment]
重复

**Comment by Stonejxn** [comment]
这个库不维护了吗
