### ISSUE TITLE
js注入时间有bug，可能导致web页第一次调用不成功

### ISSUE THREAD

**Issue by yangchong211** [yangchong211/YCWebView#17]
OnPageFinished中注入，虽然最后都会全局注入成功，但是完成时间有可能太晚，当页面在初始化调用接口函数时会等待时间过长，可能不成功，我把注入放到了onProgressChanged当进度大于80%时注入，
因为从测试看来只有进度大于这个数字页面才真正得到框架刷新加载，保证100%注入成功

**Comment by ff-frida** [comment]
onProgressChanged当进度大于80%时注入
这个80%准确吗，我也遇到这个问题了，第一次可能会失败。
如果业务是自己内部的，我可以考虑把bridge js内置。这样就不会出现先后问题了吧。
