### ISSUE TITLE
第一次加载x5webview会卡顿这个问题有解决吗

### ISSUE THREAD

**Issue by lodgkk** [yangchong211/YCWebView#2]
直接用x5webview第一次加载会卡顿,不知道这里有没有处理这个问题,因为要涉及到在x5webview初始化的时候处理,所以想问问

**Comment by yangchong211** [comment]
你也可以将webView初始化放到application中初始化，弄一个全局的webView对象。虽然有方案这样说，但是这种做法并不多……
