### ISSUE TITLE
1.1.6版本依赖不了,maven仓库上只看到1.1.2的，是没上传么？

### ISSUE THREAD

**Issue by yuxingfafu** [yangchong211/YCWebView#29]
1.1.6版本依赖不了,maven仓库上只看到1.1.2的，是没上传么？
![image](https://user-images.githubusercontent.com/7764483/68528533-0cb8b800-032f-11ea-98be-388b5f1f1290.png)

**Comment by yangchong211** [comment]
你再查下，应该已经提交上去了，
![image](https://upload-images.jianshu.io/upload_images/4432347-0c9cddef6e01726c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
