### ISSUE TITLE
tbs文件预览加载失败

### ISSUE THREAD

**Issue by xiaohaibin** [yangchong211/YCWebView#59]
同一个页面加载不同的文件后面的文件加载不出来
报：android.content.pm.PackageManager$NameNotFoundException:

**Comment by xiaohaibin** [comment]
demo使用也会复现问题

**Comment by zhaoxiuyu** [comment]
@xiaohaibin  这个库的混淆规则 怎么加的。

**Comment by xiaohaibin** [comment]
还没混淆，目前找到原因了
需要这样处理，放在   super之后去处理会出问题
 @Override
    public void onDestroy() {
        if (mDocumentReaderView != null) {
            mDocumentReaderView.onStopDisplay();
        }
        super.onDestroy();
    }
