### ISSUE TITLE
weblib使用腾讯的jar包，会引起其他lib也使用腾讯jar互相冲突，建议使用provided引用

### ISSUE THREAD

**Issue by 917163738** [yangchong211/YCWebView#71]
我改成了这样避免了重复引用腾讯包的问题
dependencies {
//    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    provided files('libs/tbs_sdk_thirdapp_v4.3.0.1148_43697_sharewithdownloadwithfile_withoutGame_obfs_20190805_175505.jar')
}

**Comment by yangchong211** [comment]
已经改为maven依赖
