### ISSUE TITLE
作者快来更新，解决jar包冲突

### ISSUE THREAD

**Issue by lucifinilsu** [yangchong211/YCWebView#73]
x5官方更新了最新的依赖,不再是jar包了,会和你这个库的jar冲突。建议你库里按这个来：api 'com.tencent.tbs.tbssdk:sdk:latest.release'

**Comment by yangchong211** [comment]
好的，收到，谢谢

**Comment by yangchong211** [comment]
1.3.0版本会更新一下，目前1.2.7版本已经更新到最新jar包呢
