### ISSUE TITLE
作者提供的jar文件与腾讯提供的jar文件的md5不同

### ISSUE THREAD

**Issue by lucifinilsu** [yangchong211/YCWebView#85]
一直不明白为什么作者一直坚持使用本地jar，X5官方早已推出了直接依赖方式：api 'com.tencent.tbs.tbssdk:sdk:latest.release'，为啥不直接使用呢？刚才看了下官方jar和你本地jar的md5，相同版本，但二者文件md5值是不同的，作者的jar是不是做了什么优化修改啥的，望告知。

**Comment by yangchong211** [comment]
之前一致采用jar依赖，现在已经改成maven远程依赖，感谢
