### ISSUE TITLE
demo本地直接依赖lib，发现部分方法是没有的，依赖远程lib是正常的。

### ISSUE THREAD

**Issue by ff-frida** [yangchong211/YCWebView#86]
[https://github.com/ff-frida/flutter_taobao_union/blob/master/tempimg/404.png](url)

下载这个demo，然后把远程依赖去掉，使用本地依赖，出现上面图片的情况，很多方法都是没有的。
这个作者能看看是什么情况吗，现在想监听page finish之后，localstroge写入数据，发现client已经在内部init的时候初始化了
看了本地lib代码和远程依赖的又不一致。。。蒙了。。

**Comment by yangchong211** [comment]
这个是因为在lib中采用implementation依赖，把这个改成api就可以了
