### ISSUE TITLE
加了这个tbs_sdk_thirdapp jar后，混淆就会出问题，程序在 X5WebUtils.init(this);这个方法处，就执行不下去。如何处理呢？

### ISSUE THREAD

**Issue by love0829** [yangchong211/YCWebView#89]
加了这个tbs_sdk_thirdapp jar后，混淆就会出问题，程序在 X5WebUtils.init(this);这个方法处，就执行不下去。如何处理呢？

![image](https://user-images.githubusercontent.com/8587160/91635963-61006600-ea2f-11ea-88f7-e42d9bdd4611.png)

建议在文档里补充混淆的添加
![image](https://user-images.githubusercontent.com/8587160/91636379-95295600-ea32-11ea-950f-2056e689a6c6.png)
下面这两句，加上去，在运行，就没有太大问题了
-keep class com.tencent.smtt.** {*;}
-dontwarn com.tencent.smtt.**
可以使引用的jar不被混淆

**Comment by yangchong211** [comment]
- 代码如下所示
    ```
    # 该包下所有的类和类成员不混淆
    -keep class com.ycbjie.webviewlib.** {
        *;
    }
    -dontwarn com.ycbjie.webviewlib.**
    ```
- 关于腾讯x5混淆
    ```
    -dontwarn dalvik.**
    -dontwarn com.tencent.smtt.**
    
    -keep class com.tencent.smtt.** {
        *;
    }
    
    -keep class com.tencent.tbs.** {
        *;
    }
    ```
好的，已经把这段x5的混淆添加到lib中了
