### ISSUE TITLE
请问怎么获取当前url加载的路径？

### ISSUE THREAD

**Issue by FynnJason** [yangchong211/YCWebView#91]
想打印出每个页面的url地址

**Comment by fangxiong** [comment]
InterWebListener的回调方法startProgress()中调用webView.url即可拿到当前页面的url

**Comment by yangchong211** [comment]
X5LogUtils.setIsLog(true);设置打开日志
然后过滤日志onPageStarted即可打印每个页面的url，如果是有重定向，则可以过滤shouldOverrideUrlLoading的日志
或者String url = mWebView.getUrl();获取url打印出来也可以
